language: python
python:
        - "3.3"
install:
        - pip install -r requirements.txt
        - pip install pep8 --use-mirrors
        - pip install pyflakes
script:
        - "pep8 --ignore=E501 ."
        - pyflakes .
